[package]
name = "starknet_forge_template"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[[target.starknet-contract]]
sierra = true
casm = true

[dependencies]
starknet = "2.2.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.5.0" }

[tool.snforge]
# exit_first = true

[tool.sncast.test3]
account = "test3"
accounts-file = "/Users/amitr/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-goerli.infura.io/v3/2f57c80fb95b4fb38725aea62bc77c1d"
